keys:
  - &personal age1sxluvsegl5a5f7mv2pnh2y9rqym8tdhdgrwwygz0yk2wljjmlpqs9y9cq2 # from public key
creation_rules:
  # binary files
  - path_regex: secrets/[^/]+\.(bin|key|pem|crt|der|p12|pfx|gpg|asc)$
    input_type: binary
    output_type: binary
    key_groups:
      - age:
          - *personal

  # supported file types
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *personal
